name = "BrandtSolver"
uuid = "383f7842-7e3d-42de-94bc-9d75093b1446"
version = "1.0.0-DEV"
authors = ["Sliem el Ela"]

[workspace]
projects = ["docs"]

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"

[sources]
FinancialMarketSimulation = {rev = "main", url = "https://github.com/sliemelela/FinancialMarketSimulation.jl"}

[compat]
CairoMakie = "0.15.8"
Combinatorics = "1.1.0"
DocStringExtensions = "0.9.5"
FinancialMarketSimulation = "1.0.0"
ForwardDiff = "1.3.2"
Interpolations = "0.16.2"
LinearAlgebra = "1.11.0"
NonlinearSolve = "4.16.0"
Printf = "1.11.0"
Random = "1.11.0"
Roots = "2.2.10"
StaticArrays = "1.9.16"
Statistics = "1.11.1"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
FinancialMarketSimulation = "873f78ff-6396-4785-a014-dd5df8284ed2"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"


[targets]
test = ["Test", "Printf", "Random", "FinancialMarketSimulation"]
