[deps]
BrandtSolver = "383f7842-7e3d-42de-94bc-9d75093b1446"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterCitations = "daee34ce-89f3-4625-b898-19384cb65244"

[sources]
BrandtSolver = {path = ".."}
